Task-55103: implement back end email integration
exoplatform/mail-integration pull request #9
Opened 2022-03-21 15:20 UTC by hassenelkamel-exo

2022-03-23 12:55 UTC, azayati requested changes
see review

2022-03-23 12:55 UTC, azayati commented on mail-integration-api/src/main/java/org/exoplatform/mailintegration/rest/model/MailIntegrationSettingEntity.java
> +package org.exoplatform.mailintegration.rest.model;
Rename it MailIntegrationSettingRestEntity instead

2022-03-23 12:55 UTC, azayati commented on mail-integration-api/src/main/java/org/exoplatform/mailintegration/service/MailIntegrationService.java
> +  MailIntegrationSetting createMailIntegration(MailIntegrationSetting connectionInformation,
```suggestion
  MailIntegrationSetting createMailIntegrationSetting(MailIntegrationSetting mailIntegrationSetting,
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/pom.xml
> +      <artifactId>social-component-core</artifactId>
why have we removed the other dependencies ?

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/service/mailIntegrationService.js
> +export function createMailIntegrationSettings(mailIntegrationSettings) {
```suggestion
export function createMailIntegrationSetting(mailIntegrationSetting) {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/service/mailIntegrationService.js
> +    body: JSON.stringify(mailIntegrationSettings)
```suggestion
    body: JSON.stringify(mailIntegrationSetting)
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/service/mailIntegrationService.js
> +export function getMailIntegrationSettingsByUserId() {
```suggestion
export function getMailIntegrationSettings() {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/webpack.prod.js
> +    mailIntegrationNotificationComponent: './src/main/webapp/vue-app/common/main.js',
```suggestion
    mailIntegrationCommonComponents: './src/main/webapp/vue-app/common/main.js',
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettingsDrawer.vue
> +    modeEdit: {
```suggestion
    editMode: {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettingsDrawer.vue
> +        this.storedPassword = this.mailIntegrationSetting.password;
where do you these variables ?

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettings.vue
> +      :mode-edit="modeEdit"
```suggestion
      :edit-mode="editMode"
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettings.vue
> +    getMailIntegrationSettingsByUserId() {
```suggestion
    getMailIntegrationSettings() {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettings.vue
> +      this.$mailIntegrationService.getMailIntegrationSettingsByUserId().then(setting => {
```suggestion
      this.$mailIntegrationService.getMailIntegrationSettings().then(setting => {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettings.vue
> +        if (setting && setting.length === 1) {
```suggestion
        if (setting && setting.length > 1) {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/common/main.js
> +  'mail-integration-notification-alert': MailIntegrationNotificationAlert,
```suggestion
  'mail-integration-alert': MailIntegrationAlert,
```
The name is confusing with the mail integration notification component, this component is a common component it should be named regardless the component in which it will be used

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/html/mailIntegrationSettings.html
> +-->
not nedded

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/html/mailIntegrationNotification.html
> +-->
not needed

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <module>mailIntegrationNotificationComponent</module>
```suggestion
        <module>mailIntegrationCommonComponents</module>
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/WEB-INF/gatein-resources.xml
> +      <path>/js/mailIntegrationNotificationComponent.bundle.js</path>
```suggestion
      <path>/js/mailIntegrationCommonComponents.bundle.js</path>
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <name>mailIntegrationNotificationComponent</name>
```suggestion
    <name>mailIntegrationCommonComponents</name>
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/package.json
> +    "chokidar": "^3.5.3"
to be removed

2022-03-23 12:55 UTC, azayati commented on mail-integration-webapp/src/main/webapp/vue-app/service/mailIntegrationService.js
> +export function checkMailConnection(connectionInformationEntity) {
```suggestion
export function checkMailConnection(mailIntegrationSetting) {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/test/resources/conf/portal/configuration.xml
> +    <import>jar:/conf/exo.mail.service-local-configuration.xml</import>
```suggestion
    <import>jar:/conf/exo.mailIntegration.service-dependencies-configuration.xml</import>
    <import>jar:/conf/exo.mailIntegration.service-local-configuration.xml</import>
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/test/resources/conf/exo.mail.service-local-configuration.xml
> +    </component>
check if needed

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/test/java/org/exoplatform/mailintegration/storage/MailIntegrationStorageTest.java
> +  public void testCreatePoll() throws Exception { // NOSONAR
```suggestion
  public void testCreateMailIntegration() throws Exception { // NOSONAR
```
please check all poll occurences

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/resources/db/changelog/mail-integration-rdbms.db.changelog-master.xml
> +<!--
header not needed for xml files

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/resources/db/changelog/mail-integration-rdbms.db.changelog-1.0.0.xml
> +            <column name="EMAIL_NAME" type="NVARCHAR(2000)">
```suggestion
            <column name="NAME" type="NVARCHAR(2000)">
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/resources/db/changelog/mail-integration-rdbms.db.changelog-1.0.0.xml
> +    <changeSet author="poll" id="1.0.0-0" dbms="oracle,postgresql,hsql">
```suggestion
    <changeSet author="mail-integration" id="1.0.0-0" dbms="oracle,postgresql,hsql">
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/resources/conf/portal/configuration.xml
> +      <name>PollRDBMSChangeLogsPlugin</name>
```suggestion
      <name>MailIntegrationRDBMSChangeLogsPlugin</name>
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/utils/MailIntegrationUtils.java
> +  public static String generateEncryptedToken(CodecInitializer codecInitializer, String tokenPlain, String remoteId) {
```suggestion
  public static String encode(CodecInitializer codecInitializer, String password) {
```
remoteId not needed

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/utils/MailIntegrationUtils.java
> +  public static String decryptUserIdentity(CodecInitializer codecInitializer, String token) {
```suggestion
  public static String decode(CodecInitializer codecInitializer, String password) {
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/utils/MailIntegrationUtils.java
> +      LOG.warn("Error generating Token", e);
```suggestion
      LOG.warn("Error when encoding", e);
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/utils/MailIntegrationUtils.java
> +      LOG.warn("Error decrypting Token", e);
```suggestion
      LOG.warn("Error when decoding", e);
```

2022-03-23 12:55 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/utils/EntityMapper.java
> +      mailIntegrationSettingEntity.setId(mailIntegrationSetting.getId() == 0 ? null : mailIntegrationSetting.getId());
```suggestion
if (mailIntegrationSetting.getId() != 0) {
      mailIntegrationSettingEntity.setId(mailIntegrationSetting.getId());
```

2022-03-23 13:01 UTC, azayati requested changes
see review

2022-03-23 13:01 UTC, azayati commented on mail-integration-api/src/main/java/org/exoplatform/mailintegration/model/MailIntegrationUserSetting.java
MailIntegrationUserSetting should be removed since there will be no corresponding entity

2022-03-23 14:37 UTC, azayati commented on mail-integration-services/pom.xml
> +      <artifactId>social-component-core</artifactId>
we will keep it

2022-03-24 09:14 UTC, hassenelkamel-exo commented on mail-integration-webapp/src/main/webapp/vue-app/mail-integration-settings/components/MailIntegrationSettingsDrawer.vue
> +        this.storedPassword = this.mailIntegrationSetting.password;
to be remove

2022-03-24 10:43 UTC, azayati requested changes
see review

2022-03-24 10:43 UTC, azayati commented on mail-integration-services/src/main/java/org/exoplatform/mailintegration/entity/MailIntegrationSettingEntity.java
>    private long              creatorId;
userId

2022-03-25 16:02 UTC, azayati approved these changes
LGTM

2022-03-25 16:03 UTC, merged